spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    topic: ${SPRING_KAFKA_TOPIC}
    bootstrap-servers: ${SPRING_KAFKA_SERVER_HOST}:${SPRING_KAFKA_SERVER_PORT}
  json:
    trusted: spring.json.trusted.packages
server:
  port: ${SERVER_PORT}